# Dockerfileが存在する場合はそちらを優先
# この設定はDockerfileがない場合のフォールバック

[phases.setup]
nixPkgs = ["python311", "ffmpeg"]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"